### ISSUE TITLE
0.7.2 版右键点击托盘图标崩溃

### ISSUE THREAD

**Issue by hosiet** [iptux-src/iptux#100]
桌面：Debian Unstable + KDE Plasma 5

如需更多调试信息可以再和我说。

```
(gdb) r
Starting program: /usr/bin/iptux 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebd4b700 (LWP 24464)]
[New Thread 0x7fffeb54a700 (LWP 24465)]
[New Thread 0x7fffe22bf700 (LWP 24466)]
[New Thread 0x7fffe1abe700 (LWP 24468)]
[New Thread 0x7fffe12bd700 (LWP 24469)]
[New Thread 0x7fffe0abc700 (LWP 24470)]
[New Thread 0x7fffcffff700 (LWP 24471)]
[Thread 0x7fffcffff700 (LWP 24471) exited]
[New Thread 0x7fffcffff700 (LWP 24472)]
[Thread 0x7fffcffff700 (LWP 24472) exited]
[New Thread 0x7fffcffff700 (LWP 24473)]
[Thread 0x7fffcffff700 (LWP 24473) exited]
[Thread 0x7fffe0abc700 (LWP 24470) exited]
[New Thread 0x7fffcffff700 (LWP 24474)]
[Thread 0x7fffcffff700 (LWP 24474) exited]

Thread 1 "iptux" received signal SIGSEGV, Segmentation fault.
iptux::StatusIcon::CreatePopupMenu (this=0x0) at ./src/iptux/StatusIcon.cpp:95
95      ./src/iptux/StatusIcon.cpp: 没有那个文件或目录.
(gdb) bt full
#0  iptux::StatusIcon::CreatePopupMenu (this=0x0) at ./src/iptux/StatusIcon.cpp:95
        menu = <optimized out>
        menuitem = <optimized out>
        image = <optimized out>
        window = <optimized out>
#1  0x00005555555823d1 in iptux::StatusIcon::onPopupMenu (statusicon=<optimized out>, button=3, time=51993433, self=<optimized out>) at ./src/iptux/StatusIcon.cpp:209
        menu = <optimized out>
#2  0x00007ffff6b18f9d in g_closure_invoke (closure=0x5555558bede0, return_value=0x0, n_param_values=3, param_values=0x7fffffffcf40, invocation_hint=0x7fffffffcec0) at ../../../../gobject/gclosure.c:804
        marshal = 0x7ffff78cb980 <_gtk_marshal_VOID__UINT_UINT>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x5555558bedc0
        __func__ = "g_closure_invoke"
#3  0x00007ffff6b2bcce in signal_emit_unlocked_R (node=node@entry=0x555555864580, detail=detail@entry=0, instance=instance@entry=0x5555558178a0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffcf40) at ../../../../gobject/gsignal.c:3635
        tmp = <optimized out>
        handler = 0x5555558be4c0
        accumulator = 0x0
        emission = {next = 0x7fffffffd3a0, instance = 0x5555558178a0, ihint = {signal_id = 124, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
        handler_list = 0x5555558be4c0
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 124
        max_sequential_handler_number = 411
        return_value_altered = 1
#4  0x00007ffff6b344a5 in g_signal_emit_valist (instance=0x5555558178a0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd130) at ../../../../gobject/gsignal.c:3391
        instance_and_params = 0x7fffffffcf40
        signal_return_type = 4
        param_values = 0x7fffffffcf58
        i = <optimized out>
        n_params = 2
        __func__ = "g_signal_emit_valist"
#5  0x00007ffff6b34ebf in g_signal_emit (instance=instance@entry=0x5555558178a0, signal_id=<optimized out>, detail=detail@entry=0) at ../../../../gobject/gsignal.c:3447
        var_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffd210, reg_save_area = 0x7fffffffd150}}
#6  0x00007ffff793cee9 in emit_popup_menu_signal (activate_time=<optimized out>, button=<optimized out>, status_icon=0x5555558178a0) at ./gtk/gtkstatusicon.c:1324
No locals.
#7  gtk_status_icon_button_press (status_icon=status_icon@entry=0x5555558178a0, event=0x555555c5c520) at ./gtk/gtkstatusicon.c:1782
        handled = 0
#8  0x00007ffff78c8a4b in _gtk_marshal_BOOLEAN__BOXED (closure=0x5555558a5830, return_value=0x7fffffffd3d0, n_param_values=<optimized out>, param_values=0x7fffffffd430, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ./gtk/gtkmarshalers.c:86
        callback = 0x7ffff793ce40 <gtk_status_icon_button_press>
        cc = 0x5555558a5830
        data1 = 0x5555558178a0
        data2 = <optimized out>
        v_return = <optimized out>
        __func__ = "_gtk_marshal_BOOLEAN__BOXED"
#9  0x00007ffff6b18f9d in g_closure_invoke (closure=0x5555558a5830, return_value=0x7fffffffd3d0, n_param_values=2, param_values=0x7fffffffd430, invocation_hint=0x7fffffffd3b0) at ../../../../gobject/gclosure.c:804
        marshal = 0x7ffff78c89e0 <_gtk_marshal_BOOLEAN__BOXED>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x5555558a5810
        __func__ = "g_closure_invoke"
#10 0x00007ffff6b2bcce in signal_emit_unlocked_R (node=node@entry=0x55555581fa00, detail=detail@entry=0, instance=instance@entry=0x555555867080, emission_return=emission_return@entry=0x7fffffffd550, instance_and_params=instance_and_params@entry=0x7fffffffd430) at ../../../../gobject/gsignal.c:3635
        tmp = <optimized out>
        handler = 0x55555581de40
        accumulator = 0x55555581f7b0
        emission = {next = 0x0, instance = 0x555555867080, ihint = {signal_id = 33, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
        handler_list = 0x55555581de40
        return_accu = 0x7fffffffd3d0
        accu = {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 33
        max_sequential_handler_number = 411
        return_value_altered = 0
#11 0x00007ffff6b33e3f in g_signal_emit_valist (instance=0x555555867080, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd600) at ../../../../gobject/gsignal.c:3401
        return_value = {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        error = 0x0
        rtype = 20
        static_scope = 0
        instance_and_params = 0x7fffffffd430
        signal_return_type = 20
        param_values = 0x7fffffffd448
        i = <optimized out>
        n_params = 1
        __func__ = "g_signal_emit_valist"
#12 0x00007ffff6b34ebf in g_signal_emit (instance=instance@entry=0x555555867080, signal_id=<optimized out>, detail=detail@entry=0) at ../../../../gobject/gsignal.c:3447
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd6e0, reg_save_area = 0x7fffffffd620}}
#13 0x00007ffff79de34c in gtk_widget_event_internal (widget=widget@entry=0x555555867080, event=event@entry=0x555555c5c520) at ./gtk/gtkwidget.c:5010
        signal_num = <optimized out>
        return_val = 0
#14 0x00007ffff79de5e7 in IA__gtk_widget_event (widget=widget@entry=0x555555867080, event=event@entry=0x555555c5c520) at ./gtk/gtkwidget.c:4807
        __func__ = "IA__gtk_widget_event"
#15 0x00007ffff78c71ec in IA__gtk_propagate_event (widget=0x555555867080, event=0x555555c5c520) at ./gtk/gtkmain.c:2501
        tmp = <optimized out>
        handled_event = <optimized out>
        __func__ = "IA__gtk_propagate_event"
#16 0x00007ffff78c75eb in IA__gtk_main_do_event (event=<optimized out>) at ./gtk/gtkmain.c:1696
        grab_widget = 0x555555867080
        window_group = <optimized out>
        tmp_list = <optimized out>
        event_widget = <optimized out>
        event = 0x555555c5c520
#17 0x00007ffff753cf2c in gdk_event_dispatch (source=source@entry=0x555555807490, callback=<optimized out>, user_data=<optimized out>) at ./gdk/x11/gdkevents-x11.c:2425
        display = <optimized out>
        event = 0x555555c5c520
#18 0x00007ffff7218fb7 in g_main_dispatch (context=0x555555807580) at ../../../../glib/gmain.c:3165
        dispatch = 0x7ffff753cee0 <gdk_event_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x555555807490
        current = 0x555555a15270
        i = 0
#19 g_main_context_dispatch (context=context@entry=0x555555807580) at ../../../../glib/gmain.c:3818
No locals.
#20 0x00007ffff72191f0 in g_main_context_iterate (context=0x555555807580, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3891
        max_priority = 2147483647
        timeout = 72
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x555555b061e0
#21 0x00007ffff7219502 in g_main_loop_run (loop=0x555555b127c0) at ../../../../glib/gmain.c:4087
        __func__ = "g_main_loop_run"
#22 0x00007ffff78c6617 in IA__gtk_main () at ./gtk/gtkmain.c:1268
        tmp_list = <optimized out>
        functions = 0x0
        init = <optimized out>
        loop = 0x555555b127c0
#23 0x000055555556fab0 in main (argc=<optimized out>, argv=<optimized out>) at ./src/main/iptux.cpp:188
        error = 0x0
        context = <optimized out>
        configPath = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x55555584b9d0 "/home/hosiet/.iptux/config.json"}, _M_string_length = 31, {_M_local_buf = "\037\000\000\000\000\000\000\000\352\336\336\367\377\177\000", _M_allocated_capacity = 31}}
        config = {fname = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x55555584b7a0 "/home/hosiet/.iptux/config.json"}, _M_string_length = 31, {_M_local_buf = "\037\000\000\000\000\000\000\000`\000\000\000\000\000\000", _M_allocated_capacity = 31}}, root = {static null = @0x5555557ceab0, static nullRef = @0x5555557ceab0, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 93824995313648, uint_ = 93824995313648, real_ = 4.6355706905689429e-310, bool_ = 240, string_ = 0x5555558447f0 "\220?\204UUU", map_ = 0x5555558447f0}, type_ = Json::objectValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 134}}
        progdt = {nickname = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdc00 "hosiet"}, _M_string_length = 6, {_M_local_buf = "hosiet\000el\000\000\000\000\000\000\200", _M_allocated_capacity = 7277944976740413288}}, mygroup = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdc20 ""}, _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}, myicon = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdc40 "icon-tux.png"}, _M_string_length = 12, {_M_local_buf = "icon-tux.png\000\000\000\200", _M_allocated_capacity = 8679971595301643113}}, path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdc60 "/home/hosiet"}, _M_string_length = 12, {_M_local_buf = "/home/hosiet\000\000\000", _M_allocated_capacity = 8027718448462129199}}, sign = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdc80 ""}, _M_string_length = 0, {_M_local_buf = "\000\274\021\366\377\177\000\000\020\034\001\000\000\000\000", _M_allocated_capacity = 140737321745408}}, codeset = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdca0 "utf-16"}, _M_string_length = 6, {_M_local_buf = "utf-16\000\000I\251\336\365\377\177\000", _M_allocated_capacity = 59584842986613}}, encode = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdcc0 "utf-8"}, _M_string_length = 5, {_M_local_buf = "utf-8\000\000\000\060\034\001\000\000\000\000", _M_allocated_capacity = 241279857781}}, palicon = 0x55555584cd10 "icon-qq.png", font = 0x55555584ccf0 "Sans Serif 10", transtip = 0x55555584ce00 "/usr/share/iptux/sound/trans.ogg", msgtip = 0x55555584cda0 "/usr/share/iptux/sound/msg.ogg", volume = 0, sndfgs = 255 '\377', netseg = 0x0, urlregex = 0x55555584e2e0, xcursor = 0x55555584cdd0, lcursor = 0x555555858380, table = 0x555555813580, timestamp = {tv_sec = 1516323492, tv_usec = 844187}, config = @0x7fffffffda60, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, flags = 0 '\000'}
        mwin = {config = @0x7fffffffda60, progdt = @0x7fffffffdbf0, statusIcon = 0x7fffffffd9a0, widset = 0x555555927b40, mdlset = 0x5555558c3ee0, tmdllist = 0x5555558b8520, accel = 0x5555558be540, timerid = 8, windowConfig = {_vptr.WindowConfig = 0x5555557aa650 <vtable for iptux::WindowConfig+16>, width = 250, height = 510, prefix = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdb10 "main_window"}, _M_string_length = 11, {_M_local_buf = "main_window\000UU\000", _M_allocated_capacity = 7956021468484690285}}}}
        cthrd = {config = @0x7fffffffda60, tcpsock = 7, udpsock = 8, server = true, pallist = 0x555555a69eb0, rgllist = 0x555555a6c480, sgmlist = 0x555555a6c610, grplist = 0x555555a6c670, brdlist = 0x555555a6c800, blacklist = 0x0, msgline = {head = 0x0, tail = 0x0, length = 0}, pbn = 1, prn = 10000, pblist = 0x0, prlist = 0x0, ecsList = 0x0, passwd = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffffffdbb0 ""}, _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}, timerid = 26, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}
        sicon = {config = @0x7fffffffda60, mwin = @0x7fffffffdab0, statusicon = 0x5555558178a0, timerid = 0, embedded = 1}
        lgsys = {fdc = 9, fds = 10}
        sndsys = {eltset = 0x1, timestamp = {tv_sec = 140737351937123, tv_usec = 1}, persist = false}
        port = <optimized out>
```

**Comment by lidaobing** [comment]
closed
