### ISSUE TITLE
crash in iptux::DialogBase::UpdateFileSendUI -> g_datalist_get_data

### ISSUE THREAD

**Issue by lidaobing** [iptux-src/iptux#115]
```
(gdb) bt full
#0  0x00007ffff7aefe99 in g_datalist_get_data () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00005555555b09a7 in iptux::DialogBase::UpdateFileSendUI(iptux::DialogBase*) (dlggrp=0x555555c93070) at /home/lidaobing/workspace/iptux/src/iptux/DialogBase.cpp:827
        model = 0x555555e24e80
        iter = {stamp = 0, user_data = 0x2ffffd8a0, user_data2 = 0x0, user_data3 = 0x7ffff57023fe <__GI___libc_free+110>}
        progresstip = "\000\000\000\000\000\000\000\000\000\361\347\321\f\330\f.\000\000\000\000\000\000\000\000@g\201UUU\000\000\320\362\312UUU\000\000\320\362\312UUU\000\000\260\214\310UUU\000\000\240\330\377\377\377\177\000\000\260\220\201UUU\000\000\376#p\365\377\177\000\000\260\220\201UUU\000\000\373\062|\360\377\177\000\000Ȑ\201UUU\000\000@g\201UUU\000\000\300b\201UUU\000\000\000\361\347\321\f\330\f.@g\201UUU\000\000@g\201UUU\000\000\320\362\312UUU\000\000\320\362\312UUU\000\000\260\214\310UUU\000\000PM\317\364\377\177\000\000\000\000\000\000\000\000\000\000 \331\377\377\377\177", '\000' <repeats 26 times>...
        treeview = 0x55555558b109
        pbar = 0x5555557dbfc0
        progress = 0
        sentsize = 80
        theme = 0x555555865a40
        pixbuf = 0x555555b87a40
        statusfile = 0x5555555b554d "tip-finish"
        file = 0x7fffffffd790
#2  0x00007ffff6ed2090 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007ffff7b0c8a3 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7b0be25 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7b0c1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7b0c27c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff6735c4d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00005555555768ae in iptux::Application::run(int, char**) (this=0x7fffffffddf0, argc=1, argv=0x7fffffffdf88) at /home/lidaobing/workspace/iptux/src/iptux/Application.cpp:131
#9  0x00005555555765c3 in main(int, char**) (argc=1, argv=0x7fffffffdf88) at /home/lidaobing/workspace/iptux/src/main/iptux.cpp:147
        error = 0x0
        context = 0x5555557e6340
        configPath = "/home/lidaobing/.iptux/config.json"
        config =
            {fname = "/home/lidaobing/.iptux/config.json", root = {static null = @0x5555557e54d0, static nullRef = @0x5555557e54d0, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 93824997452208, uint_ = 93824997452208, real_ = 4.6355707962278457e-310, bool_ = 176, string_ = 0x555555a4e9b0 "@ƺUUU", map_ = 0x555555a4e9b0}, type_ = Json::objectValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 0}}
        app = {config = @0x7fffffffde40, data = 0x5555557e8540, app = 0x5555557f3100, window = 0x5555557dbfc0, shareFile = 0x0}
```

**Comment by lidaobing** [comment]
dup with #356
