### ISSUE TITLE
crash on dialogpeer

### ISSUE THREAD

**Issue by lidaobing** [iptux-src/iptux#127]
How to reproduce:

1. send a file to yourself
2. click accept and choose a dir
3. click "Refuse"

expected:
* nothing happened

what happened:
* crash as follows

```
(gdb) bt full
#0  0x00007ffff5955961 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff5956c4b in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5956d9f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5c32ae4 in g_object_get_data () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00005555555aeaf9 in iptux::DialogPeer::RemoveSelectedRcv(_GtkWidget*) (widget=0x555555ced950) at /home/lidaobing/workspace/lidaobing/iptux/src/iptux/DialogPeer.cpp:1197
        model = 0x77221957a110ff00
        TreeSel = 0x-3f8f000000000000
        iter = {stamp = 0, user_data = 0x406fc00000000000, user_data2 = 0xc071000000000000, user_data3 = 0x406fc00000000000}
        file = 0x7ffff6ffa891 <gdk_cairo_get_clip_rectangle+49>
        dlg = 0x555555cf3be0
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xe5e8ef8948005869: 
        list = #5  0x00007ffff5c291d6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff5c4478f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff5c44ebf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
```

**Comment by lidaobing** [comment]
```
(lldb) f 4
frame #4: 0x000000010002b3ee iptux`iptux::DialogPeer::RemoveSelectedRcv(widget=0x000000010156d680) at DialogPeer.cpp:1201
   1198	  DialogPeer *dlg;
   1199	  GList *list;
   1200
-> 1201	  dlg = (DialogPeer *)(g_object_get_data(G_OBJECT(widget), "dialog"));
   1202	  model = gtk_tree_view_get_model(GTK_TREE_VIEW(widget));
   1203	  //从中心结点删除
   1204	  TreeSel = gtk_tree_view_get_selection(GTK_TREE_VIEW(widget));
```
