### ISSUE TITLE
ubuntu 18.04  iptux (0.7.4-1) 添加ipv4网段点击确认后立刻退出

### ISSUE THREAD

**Issue by xingxingge** [iptux-src/iptux#207]
添加网段，导入网段，点击确认时，程序都会退出，请问什么原因导致的？谢谢！

**Comment by lidaobing** [comment]
有拿到 backtrace 么？

**Comment by lidaobing** [comment]
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff68eac03 in Json::Value::Value(char const*) ()
   from /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1
#2  0x000055555557bd02 in iptux::NetSegment::ToJsonValue() const ()
#3  0x000055555557e567 in iptux::ProgramData::WriteNetSegment() ()
#4  0x000055555557f12d in iptux::ProgramData::WriteProgData() ()
#5  0x000055555558fbe7 in iptux::DataSettings::ResetDataEntry(_GtkWidget*) ()
#6  0x00007ffff6b12f6d in g_closure_invoke ()
```

**Comment by xingxingge** [comment]
thanks，I will try

**Comment by xingxingge** [comment]
能提供解决这个bug编译好的so文件么？我这环境死活编译不成功

**Comment by lidaobing** [comment]
@xingxingge 给一下编译失败的信息。
