### ISSUE TITLE
Receiving shared folder causes the app to crash

### ISSUE THREAD

**Issue by archerallstars** [iptux-src/iptux#472]
Whenever I tried to receive a shared folder, the app crashed. 

However, I can receive a file without crashing.

App Version: Snap Store Stable
OS: Ubuntu 21.04

**Comment by lidaobing** [comment]
@kreaninw I can't reproduce this bug, can you tell me how to reproduce, or give me a backtrace?

thanks.

**Comment by kreaninw** [comment]
> @kreaninw I can't reproduce this bug, can you tell me how to reproduce, or give me a backtrace?
> 
> thanks.

Folder/directory sharing causes the app to crash as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/125356677-87bc4800-e334-11eb-8b56-59bd658d2f11.mp4

And here, everything works as expected when I share a file instead of a folder, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/125356821-bfc38b00-e334-11eb-85bb-c5aa8d98e552.mp4

**Comment by lidaobing** [comment]
@kreaninw thanks

**Comment by lidaobing** [comment]
finally caught it, sounds stackoverflow

```
#7661 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c28e8 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7662 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c2d28 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7663 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c3168 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7664 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c35a8 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7665 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c39e8 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7666 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c3e28 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7667 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffee7c4268 "/home/lidaobing/Desktop/iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7668 0x0000fffff7f469f4 in iptux::AnalogFS::mkdir(char const*, unsigned int) (this=0xffffee7c47a8, dir=0xffffd80037c0 "iptux-share", mode=511) at ../src/iptux-core/internal/AnalogFS.cpp:137
#7669 0x0000fffff7f4cd4c in iptux::RecvFileData::RecvDirFiles() (this=0xffffd8008810) at ../src/iptux-core/internal/RecvFileData.cpp:270
#7670 0x0000fffff7f4be78 in iptux::RecvFileData::RecvFileDataEntry() (this=0xffffd8008810) at ../src/iptux-core/internal/RecvFileData.cpp:77
#7671 0x0000fffff7f13cb4 in iptux::CoreThread::RecvFile(iptux::FileInfo*) (this=0xaaaaaac4f620, file=0xaaaaab258070) at ../src/iptux-core/CoreThread.cpp:663
#7672 0x0000fffff7f393f8 in std::__invoke_impl<void, void (iptux::CoreThread::*)(iptux::FileInfo*), iptux::CoreThread*, iptux::FileInfo*>(std::__invoke_memfun_deref, void (iptux::CoreThread::*&&)(iptux::FileInfo*), iptux::CoreThread*&&, iptux::FileInfo*&&) (__f=@0xaaaaaae518e8: (void (iptux::CoreThread::*)(class iptux::CoreThread * const, class iptux::FileInfo *)) 0xfffff7f13c40 <iptux::CoreThread::RecvFile(iptux::FileInfo*)>, __t=@0xaaaaaae518e0: 0xaaaaaac4f620) at /usr/include/c++/11/bits/invoke.h:74
#7673 0x0000fffff7f39174 in std::__invoke<void (iptux::CoreThread::*)(iptux::FileInfo*), iptux::CoreThread*, iptux::FileInfo*>(void (iptux::CoreThread::*&&)(iptux::FileInfo*), iptux::CoreThread*&&, iptux::FileInfo*&&) (__fn=@0xaaaaaae518e8: (void (iptux::CoreThread::*)(class iptux::CoreThread * const, class iptux::FileInfo *)) 0xfffff7f13c40 <iptux::CoreThread::RecvFile(iptux::FileInfo*)>) at /usr/include/c++/11/bits/invoke.h:96
#7674 0x0000fffff7f38ff4 in std::thread::_Invoker<std::tuple<void (iptux::CoreThread::*)(iptux::FileInfo*), iptux::CoreThread*, iptux::FileInfo*> >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=0xaaaaaae518d8) at /usr/include/c++/11/bits/std_thread.h:259
#7675 0x0000fffff7f38c98 in std::thread::_Invoker<std::tuple<void (iptux::CoreThread::*)(iptux::FileInfo*), iptux::CoreThread*, iptux::FileInfo*> >::operator()() (this=0xaaaaaae518d8) at /usr/include/c++/11/bits/std_thread.h:266
#7676 0x0000fffff7f38944 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (iptux::CoreThread::*)(iptux::FileInfo*), iptux::CoreThread*, iptux::FileInfo*> > >::_M_run() (this=0xaaaaaae518d0) at /usr/include/c++/11/bits/std_thread.h:211
#7677 0x0000fffff6e831fc in  () at /lib/aarch64-linux-gnu/libstdc++.so.6
#7678 0x0000fffff6c4d5c8 in start_thread (arg=0x0) at ./nptl/pthread_create.c:442
#7679 0x0000fffff6cb5edc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```
