### ISSUE TITLE
better exit message when start iptux from snap twice

### ISSUE THREAD

**Issue by fenghuan1994** [iptux-src/iptux#475]
```
🐧 lidaobing@para1 ~$ ps aux | grep iptux
lidaobi+   24104  1.2  1.7 618024 35584 ?        Sl   13:22   1:37 /snap/iptux/371/usr/bin/iptux
lidaobi+   26341  0.0  0.0   9044   664 pts/0    S+   15:36   0:00 grep --color=auto iptux
🐧 lidaobing@para1 ~$ /snap/bin/iptux 
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

(iptux:26347): GLib-GObject-CRITICAL **: 15:36:39.140: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

-----
oringal message:

报错信息如下
fenghuan@fenghuan:/code1/Android11_MP3$ iptux 

(iptux:12761): GLib-GObject-CRITICAL **: 10:34:24.919: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by lidaobing** [comment]
@fenghuan1994 
1. 发一下版本号: `iptux --version`
2. 建议安装 snap 版本， `sudo snap install iptux`

**Comment by fenghuan1994** [comment]
是snap安装的。
已解决，估计是更新了，但是没有彻底杀死后台。kill掉进程后可打开。
多谢解答！

**Comment by lidaobing** [comment]
```

**Comment by lidaobing** [comment]
```
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000fffff71b5d68 in g_logv () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#2  0x0000fffff71b5f38 in g_log () at /lib/aarch64-linux-gnu/libglib-2.0.so.0                                                                                                     
#3  0x0000aaaaaaaf6ff0 in iptux::Application::~Application() (this=0xffffffffeac8, __in_chrg=<optimized out>) at ../src/iptux/Application.cpp:91                                  
#4  0x0000aaaaaaaf4940 in main(int, char**) (argc=1, argv=0xffffffffed08) at ../src/main/iptux.cpp:166                                                                            
(gdb) f 3                                                                                                                                                                         
#3  0x0000aaaaaaaf6ff0 in iptux::Application::~Application (this=0xffffffffeac8, __in_chrg=<optimized out>) at ../src/iptux/Application.cpp:91                                    
91        g_object_unref(menuBuilder);                                                                                                                                            
```
