### ISSUE TITLE
UpdateFileSendUI函数出现两处段错误

### ISSUE THREAD

**Issue by nabice** [iptux-src/iptux#56]
在发送接收文件时，发现断在这里了。
treeview = GTK_TREE_VIEW(g_datalist_get_data(&(dlggrp->widset),
                                                 "file-send-treeview-widget"));

和

    pbar = GTK_WIDGET(g_datalist_get_data(&(dlggrp->widset),
                                          "file-send-progress-bar-widget"));

具体溢出的函数另一个不记得了，有一个是：gtk_tree_model_get_valist

**Comment by nabice** [comment]
Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209     ../sysdeps/x86_64/multiarch/../strcmp.S: 没有那个文件或目录.
(gdb) list
204     in ../sysdeps/x86_64/multiarch/../strcmp.S
(gdb) where
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
#1  0x00007ffff7b00863 in g_datalist_get_data () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x0000000000415476 in DialogBase::UpdateFileSendUI (dlggrp=0x887bd0) at DialogBase.cpp:877
#3  0x00007ffff71ffce7 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#4  0x00007ffff7b1b703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7b1ace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7b1b048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7b1b30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff75c0447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x000000000040b82f in main (argc=1, argv=0x7fffffffe038) at iptux.cpp:54
