### ISSUE TITLE
crash on DialogPeer::~DialogPeer

### ISSUE THREAD

**Issue by lidaobing** [iptux-src/iptux#74]
export G_DEBUG=fatal-warnings

```
(gdb) bt
#0  0x00007ffff6b54961 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff6b55c4b in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6b55d9f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6b4db0c in g_source_remove () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000055555557ff5a in DialogPeer::~DialogPeer() ()
#5  0x000055555557ff79 in DialogPeer::~DialogPeer() ()
#6  0x00007ffff6e27f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff6e3acde in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff6e434b5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6e43ecf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff78ea720 in gtk_object_dispose (gobject=0x555555846bf0) at ./gtk/gtkobject.c:421
#11 0x00007ffff6e2e688 in g_object_run_dispose () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6e27f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6e3acde in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff6e434b5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff6e43ecf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7820475 in gtk_real_button_released (button=0x5555559d0b60) at ./gtk/gtkbutton.c:1712
#17 0x00007ffff6e27f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6e3adae in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6e434b5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff6e43ecf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff781f3f9 in gtk_button_button_release (widget=widget@entry=0x5555559d0b60, event=<optimized out>) at ./gtk/gtkbutton.c:1604
#22 0x00007ffff78c4b7b in _gtk_marshal_BOOLEAN__BOXED (closure=0x555555815630, return_value=0x7fffffffd520, n_param_values=<optimized out>, param_values=0x7fffffffd580, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtkmarshalers.c:83
#23 0x00007ffff6e27f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff6e3a758 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff6e42e4f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff6e43ecf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff79daf9c in gtk_widget_event_internal (widget=widget@entry=0x5555559d0b60, event=event@entry=0x555555989f40) at ./gtk/gtkwidget.c:5017
#28 0x00007ffff79db237 in IA__gtk_widget_event (widget=widget@entry=0x5555559d0b60, event=event@entry=0x555555989f40) at ./gtk/gtkwidget.c:4814
#29 0x00007ffff78c331c in IA__gtk_propagate_event (widget=0x5555559d0b60, event=0x555555989f40) at ./gtk/gtkmain.c:2520
#30 0x00007ffff78c371b in IA__gtk_main_do_event (event=<optimized out>) at ./gtk/gtkmain.c:1710
#31 0x00007ffff7538f0c in gdk_event_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ./gdk/x11/gdkevents-x11.c:2425
#32 0x00007ffff6b4efb7 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff6b4f1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff6b4f502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff78c2727 in IA__gtk_main () at ./gtk/gtkmain.c:1282
#36 0x000055555556dd52 in main ()
```

**Comment by lidaobing** [comment]
fixed in #75
